export const products = [
  {
    id: 1,
    name: 'Classic Chocolate',
    category: 'chocolate',
    description:
      'The original and beloved — rich dark chocolate ganache with a melt-in-your-mouth center, hand-rolled in chocolate sprinkles.',
    ingredients: 'Dark chocolate, sweetened condensed milk, butter, chocolate sprinkles',
    tasteNotes: 'Rich · Fudgy · Intensely chocolatey',
    pricePerUnit: 2.5,
    priceBox12: 28,
    priceBox24: 52,
    emoji: '🍫',
    gradient: 'from-amber-900 to-stone-800',
    featured: true,
  },
  {
    id: 2,
    name: 'Pistachio',
    category: 'nutty',
    description:
      'Creamy white chocolate base with a luscious pistachio filling, rolled in vibrant crushed pistachio crumbs.',
    ingredients: 'White chocolate, sweetened condensed milk, butter, roasted pistachios',
    tasteNotes: 'Creamy · Nutty · Delicately sweet',
    pricePerUnit: 3.0,
    priceBox12: 33,
    priceBox24: 62,
    emoji: '🟢',
    gradient: 'from-green-800 to-emerald-700',
    featured: true,
  },
  {
    id: 3,
    name: 'Coconut (Beijinho)',
    category: 'fruity',
    description:
      'A beloved Brazilian classic — sweet coconut brigadeiro rolled in shredded coconut and crowned with a whole clove.',
    ingredients: 'Coconut milk, sweetened condensed milk, butter, shredded coconut',
    tasteNotes: 'Tropical · Sweet · Light',
    pricePerUnit: 2.5,
    priceBox12: 28,
    priceBox24: 52,
    emoji: '🥥',
    gradient: 'from-yellow-200 to-amber-200',
    featured: true,
  },
  {
    id: 4,
    name: 'Passion Fruit',
    category: 'fruity',
    description:
      'Tangy passion fruit ganache nestled in a sweet white chocolate shell — a tropical explosion in every single bite.',
    ingredients: 'Passion fruit pulp, white chocolate, sweetened condensed milk, butter',
    tasteNotes: 'Tangy · Tropical · Refreshing',
    pricePerUnit: 3.0,
    priceBox12: 33,
    priceBox24: 62,
    emoji: '🌟',
    gradient: 'from-yellow-500 to-orange-400',
    featured: false,
  },
  {
    id: 5,
    name: 'Strawberry',
    category: 'fruity',
    description:
      'Bright strawberry brigadeiro rolled in delicate pink sugar crystals — sweet, fruity, and perfectly pretty.',
    ingredients: 'Strawberry, white chocolate, sweetened condensed milk, butter, pink sugar',
    tasteNotes: 'Sweet · Fruity · Vibrant',
    pricePerUnit: 2.75,
    priceBox12: 30,
    priceBox24: 56,
    emoji: '🍓',
    gradient: 'from-rose-500 to-pink-400',
    featured: false,
  },
  {
    id: 6,
    name: 'Nutella & Hazelnut',
    category: 'nutty',
    description:
      'Indulgent Nutella-swirled brigadeiro rolled in crushed roasted hazelnuts — pure decadence in a single bite.',
    ingredients: 'Nutella, sweetened condensed milk, butter, crushed hazelnuts',
    tasteNotes: 'Indulgent · Rich · Nutty',
    pricePerUnit: 3.0,
    priceBox12: 33,
    priceBox24: 62,
    emoji: '🌰',
    gradient: 'from-amber-700 to-orange-800',
    featured: false,
  },
]
